### ISSUE TITLE
Comentarios sobre el ejercicio

### ISSUE THREAD

**Issue by m4n50n** [juanmism/Instagram-with-bootstrap#1]
Hola Juanmi,

muy bien trabajado este ejercicio👌 Hay algunas cosas mejorables pero que ya te he comentado en otros ejercicios.

Lo único:
- En la parte de vista en grid, lo veo así:
![image](https://user-images.githubusercontent.com/92524023/201519355-ee9f28ee-26ef-40f1-aa22-7547092d2496.png)

Realmente parece que hay espacios inferiores entre algunas imágenes, pero es porque las imágenes no ocupan todo el espacio de su div. De hecho, si pusiera todas las imágenes iguales:
![image](https://user-images.githubusercontent.com/92524023/201519463-0d5aebbd-b2dd-4ddb-8981-6cc74cdea13f.png)

se ve que no hay espaciado vertical entre las imágenes. Aquí tendrías que aplicar algún margin que lo hiciera.

**Comment by juanmism** [comment]
Ya lo he corregido y creo que está correcto.
